name: pytest # this is the name of workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    types: [opened]
jobs:

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: pre - checkout
        run: |
          pwd
          ls -la
      - name: checkout code
        uses: actions/checkout@v3
      - name: after - checkout
        run: |
          pwd
          ls -la
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: |
          pytest
          pwd
