name: pytest # this is the name of workflow
on: workflow_dispatch #define how to trigger this workflow, workflow_dispatch means trigger it manually

jobs:

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: clone github actions repository
        run: |
          git clone https://github.com/Shawn71/github-actions-python
          cd github-actions-python
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: |
          pytest
          pwd
